export default {
  // baseUrl: 'http://10.0.0.72:7001/api/',
  // imageBaseUrl: 'http://10.0.0.72:7001/',
  baseUrl: 'http://10.0.0.101/TheDigitalCoachEnc/public/api/',
  imageBaseUrl: 'http://10.0.0.101/TheDigitalCoachEnc/public/',
  // baseUrl: 'http://112.196.30.243:9000/api/',
  // imageBaseUrl: 'http://112.196.30.243:9000/',
  authorization: 'Authorization',
  userType: 'userType',
  token: 'token',
  get: 'GET',
  post: 'POST',
  firstLoginKey: 'FirstLogin',
  name: 'name',
  true: 'true',
  picture: 'picture',
  accreditationStatus: 'accreditation_status',
  onlineStatus: 'online_status',
  subscriptionStatus: 'subscription_status',
  subscriptionEndDate: 'subscription_end_date',
  subscriptionId: 'subscription_id',
  rating: 'rating',
  totalReviews: 'total_reviews',
  coachAGB: 'coach-mobile-version',
  coacheeAGB: 'coachee-mobile-version',
  whatsCoachingEN: 'what_is_coaching_en',
  whatsCoachingDE: 'what_is_coaching_de',
  faqEN: 'faq_user_en',
  faqDE: 'faq_user_de',
  faqCoachDE: 'faq_coach_de',
  faqCoachEN: 'faq_coach_en',
  policyEN: 'privacy_policy_en',
  policyDE: 'privacy_policy_de',
}
